apiVersion: batch/v1
kind: Job
metadata:
  name: colorize-job
spec:
  template:
    metadata:
      labels:
        app: colorize-job
    spec:
      imagePullSecrets:
      - name: private-registry-auth
      containers:
      - name: colorize-container
        image: registry.datexis.com/ypwm9256/colorize-app:latest
        resources:
          limits:
            nvidia.com/gpu: 1
        env:
          - name: BASE_PATH
            value: "/volume/data"
          - name: EPOCHS
            value: "10"
        volumeMounts:
        - name: data-volume
          mountPath: /volume
      nodeSelector:
        gpu: v100 # C'est ici qu'on demande spécifiquement la V100
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: pvc-color
      restartPolicy: Never