apiVersion: v1
kind: Pod
metadata:
  name: tool-pod-color
spec:
  containers:
  - args:
    - while true; do sleep 30; done;
    command:
    - /bin/bash
    - -c
    - --
    image: debian
    name: tool-pod-color
    volumeMounts:
    - mountPath: /volume
      name: data-volume
  volumes:
  - name: data-volume
    persistentVolumeClaim:
      claimName: pvc-color
  restartPolicy: Never